stuff_database = [
    {
        "name": "iPhone 8 mini",
        "price": 300,
        "memory": 128,
        "ram": 8,
        "camera": 12,
        "description": "Самая дешевая модель iPhone",
    },
    {
        "name": "iPhone 14",
        "price": 1000,
        "memory": 128,
        "ram": 8,
        "camera": 12,
        "description": "Телефон будущего, уже сегодня!",
    },
    {
        "name": "Samsung Galaxy S23",
        "price": 900,
        "memory": 256,
        "ram": 12,
        "camera": 108,
        "description": "Камера такая острая, что сможет увидеть даже ваши ошибки",
    },
    {
        "name": "Google Pixel 7",
        "price": 850,
        "memory": 128,
        "ram": 8,
        "camera": 16,
        "description": "Для тех, кто хочет получить стоковый Android и хорошие фотки",
    },
    {
        "name": "OnePlus 9T",
        "price": 700,
        "memory": 128,
        "ram": 8,
        "camera": 48,
        "description": "Зарядка быстрее, чем ваш кофе",
    },
    {
        "name": "Xiaomi Mi 12",
        "price": 600,
        "memory": 128,
        "ram": 6,
        "camera": 64,
        "description": "Бюджетный флагман для ценителей вкуса",
    },
    {
        "name": "Sony Xperia 3",
        "price": 1100,
        "memory": 256,
        "ram": 12,
        "camera": 20,
        "description": "Телефон для тех, кто скучал по кнопке для камеры",
    },
    {
        "name": "Huawei P60",
        "price": 800,
        "memory": 128,
        "ram": 8,
        "camera": 50,
        "description": "Для любителей ночной съемки и без Google Play",
    },
    {
        "name": "Nokia 10 PureView",
        "price": 750,
        "memory": 128,
        "ram": 6,
        "camera": 48,
        "description": "Nokia вернулась, и у нее есть змейка!",
    },
    {
        "name": "LG Velvet 2",
        "price": 650,
        "memory": 128,
        "ram": 8,
        "camera": 32,
        "description": "Потому что жизнь хороша",
    },
    {
        "name": "Asus ROG Phone 6",
        "price": 1000,
        "memory": 512,
        "ram": 16,
        "camera": 64,
        "description": "Играй как профи, заряжай как новичок",
    },
    {
        "name": "Motorola Edge Plus",
        "price": 700,
        "memory": 128,
        "ram": 8,
        "camera": 108,
        "description": "Край к краю, пиксель к пикселю",
    },
    {
        "name": "Realme X4 Pro",
        "price": 450,
        "memory": 128,
        "ram": 8,
        "camera": 48,
        "description": "Экономия без потерь в качестве",
    },
    {
        "name": "Oppo Find X4",
        "price": 900,
        "memory": 256,
        "ram": 12,
        "camera": 50,
        "description": "Найди X, но без математики",
    },
    {
        "name": "BlackBerry Secure",
        "price": 1200,
        "memory": 128,
        "ram": 8,
        "camera": 12,
        "description": "Для тех, кто еще помнит, что такое физическая клавиатура",
    },
    {
        "name": "Fairphone 4",
        "price": 500,
        "memory": 64,
        "ram": 4,
        "camera": 12,
        "description": "Этичный выбор для заботливого потребителя",
    },
]